-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.injuries
(
    injury_id serial NOT NULL,
    player_id integer NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    location character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    description text COLLATE pg_catalog."default",
    feelings text COLLATE pg_catalog."default",
    next_visit timestamp without time zone,
    CONSTRAINT injuries_pkey PRIMARY KEY (injury_id),
    CONSTRAINT injuries_player_id_key UNIQUE (player_id)
);

CREATE TABLE IF NOT EXISTS public.players
(
    player_id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contract_ends date NOT NULL,
    image character varying(255) COLLATE pg_catalog."default" NOT NULL,
    statistics_id integer,
    injury_id integer,
    CONSTRAINT players_pkey PRIMARY KEY (player_id)
);

CREATE TABLE IF NOT EXISTS public.statistics
(
    statistics_id serial NOT NULL,
    player_id integer NOT NULL,
    goals integer DEFAULT 0,
    assists integer DEFAULT 0,
    passes_completed integer DEFAULT 0,
    distance_covered double precision DEFAULT 0,
    fouls integer DEFAULT 0,
    yellow_cards integer DEFAULT 0,
    red_cards integer DEFAULT 0,
    shots_on_target integer DEFAULT 0,
    saves integer DEFAULT 0,
    feedback text COLLATE pg_catalog."default",
    CONSTRAINT statistics_pkey PRIMARY KEY (statistics_id),
    CONSTRAINT statistics_player_id_key UNIQUE (player_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" DEFAULT 'player'::character varying,
    player_id integer,
    changed_password boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (username)
);

ALTER TABLE IF EXISTS public.injuries
    ADD CONSTRAINT fk_player FOREIGN KEY (player_id)
    REFERENCES public.players (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS injuries_player_id_key
    ON public.injuries(player_id);


ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT fk_injury FOREIGN KEY (injury_id)
    REFERENCES public.injuries (injury_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT players_injury_id_fkey FOREIGN KEY (injury_id)
    REFERENCES public.injuries (injury_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT players_statistics_id_fkey FOREIGN KEY (statistics_id)
    REFERENCES public.statistics (statistics_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.players (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;